src/touchegg/gestures/factory/GestureFactory.cpp
This fixes a compilation issue with gcc 6.x:
error: call of overloaded ‘abs(float&)’ is ambiguous
=> explicitly include cmath

src/touchegg/gestures/collector/GestureCollector.cpp
"Avaliable gestures" => "Available gestures"
=> Fixed misspelling 'Avaliable gestures'

CHANGELOG, README.md, src/touchegg/Touchegg.h, src/touchegg/gestures/collector/GestureCollector.h, src/touchegg/gestures/handler/GestureHandler.cpp, src/touchegg/windows/WindowListener.h
Some of them were found by codespell.
Signed-off-by: Stefan Weil <sw@weilnetz.de>
=> Fix some typos in English comments and documentation

README.md
For Keyboard shortcuts (SEND_KEYS), `<on>` and `<decreaseKeys>` are only used when `<repeat>` is `false` and `true` respectively. Previously this was documented the wrong way around in README.md.
Also improved the wording of that section and added language identifiers to code blocks to enable syntax highlighting on GitHub.
=> Fix SEND_KEY documentation and improve README.md

debian/control, debian/rules, debian/touchegg.install
This also allows us to remove the .install files as there is only one package.
=> debian: Use the modern dbgsym package instead of the handmade -dbg one

README.md
This improves formatting, fixes terminology and adds some more details about where to find keycodes for special keys and how to use keys that are not already mapped in X.
=> Improve documentation about keysyms

.gitignore, README.md, installation/touchegg.conf, src/actions/action.cpp, src/actions/action.h, src/actions/animated-action.cpp, src/actions/repeated-action.cpp, src/actions/repeated-action.h, src/actions/run-command.cpp, src/actions/run-command.h, src/actions/send-keys.cpp, src/actions/send-keys.h
Partly fixes #419 
1. Notice that `send-keys` and `run-command` are very similar, abstract that into `repeated-action`
2. Make `repeated-action` respect animation threshold (even though there are no animations there)
3. Notice that `repeated-action` and `animated-action` use threshold in the same way, abstract that into `action`
Now the only action that doesn't respect threshold is `mouse-click`, but it's pretty different in usage from the others, so I'm not sure. It's used for tablets, right? What completion percentages are emitted there for gestures?
=> Fix #419 for send-keys and run-command

src/window-system/x11-cairo-surface.cpp
Hi! So I have background-blur enabled by default on all my windows (I use [picom](https://github.com/yshui/picom)) and when an animation ran it blurred my whole screen.
I couldn't find a way to select the window that displays the animations, so I added the `WM_NAME` (line 62) and `WM_CLASS` (line 66) properties.
I don't know if there is a better way to cast a `std::string` to `char*`, and I'm not sure if you want the property to not have the accent mark (I think it should be fine because [`WM_NAME` and `WM_CLASS` are strings encoded with ISO Latin-1 characters](https://tronche.com/gui/x/icccm/sec-2.html#s-2.7.1) and [é is included in that set](https://en.wikipedia.org/wiki/ISO/IEC_8859-1)).
=> Add WM_NAME, WM_CLASS properties to cairo surface

src/daemon/daemon-server.cpp
Hi again! I don't know if this would be better as an issue, but here's my bug report: 
1. Run both daemon and client
2. Kill the client
3. Make a gesture
I think it should print the string on line https://github.com/JoseExposito/touchegg/blob/53aa6e8ddf2300912e202161b1b5844f743d199b/src/daemon/daemon-server.cpp#L107
The daemon crashes with exit code 141 (SIGPIPE) because https://github.com/JoseExposito/touchegg/blob/53aa6e8ddf2300912e202161b1b5844f743d199b/src/daemon/daemon-server.cpp#L104 tries to write to a closed socket
* Version of Touchégg: 2.0.5
* Operating System: Arch Linux
* Desktop Environment: i3
My solution was changing the `write` call to a `send` with option `MSG_NOSIGNAL` so that it doesn't crash when writing to a closed socket and instead returns an error. I basically did …
=> Fix crash when sending an event to closed socket

cmake/check-code-style.cmake
I think you meant to use the `PYTHON_EXEC` variable
=> Fix Python2 search in CMake code style check

README.md, src/actions/action-factory.cpp, src/actions/action-type.h, src/actions/fullscreen-window.cpp, src/actions/fullscreen-window.h, src/window-system/window-system.h, src/window-system/x11.cpp, src/window-system/x11.h
This PR adds a fullscreen action named `FULLSCREEN_WINDOW` that toggles the `_NET_WM_STATE_FULLSCREEN` atom on windows instead of the `_NET_WM_STATE_MAXIMIZED_VERT` and `_NET_WM_STATE_MAXIMIZED_HORZ`.
It is useful for tiling window managers that don't care about the other atoms, like i3: https://i3wm.org/docs/hacking-howto.html#_net_wm_state
=> Add fullscreen action

src/utils/color.cpp
Remove gtk_events_pending (deprecated in GTK 4) since a GLib event loop is already used
=> Fix #443 Arch Linux: Intermittent crash freeing Gesture unique_ptr

.github/workflows/build.yml
A GitHub Action for building Debian packages.
* Builds a deb package automatically from each commit
* Currently builds for `amd64`, `arm64` and `armhf`, but can be extended
This is not a complete CI workflow, as it handles bumping the changelog for unreleased changes (commits after the last release), and as such does not produce "final" changelogs. It could be extended to produce artifacts for releases, if desired.
Here is how the changelog is currently prepended by the workflow:
```
touchegg (2.0.6~1.gbp1d5dc0) UNRELEASED; urgency=medium
** SNAPSHOT build @1d5dc0609f723e72f2b93bc502d5bc677729f02f **
[ root ]
* UNRELEASED
-- José Expósito <jose.exposito89@gmail.com>  Tue, 12 Jan 2021 16:34:36 +0000
```
=> Add CI build workflow

CMakeLists.txt, installation/README.md, installation/touchegg.service.in, src/utils/paths.cpp
I tried to improve portability by removing hardcoded paths and configure files in CMake where needed.
This makes it possible to build and use on non-FHS distros such as NixOS (discussion [here](https://discourse.nixos.org/t/creating-a-simple-derivation-for-touchegg-but-the-binary-returns-an-error/11801/8)).
=> Improved portability

README.md, src/utils/client-lock.cpp
While packaging the current version for Void Linux (https://github.com/void-linux/void-packages/pull/31123) I noticed the build failing when compiling against [musl](https://musl.libc.org/). This is fixed by including `fcntl.h` for the definition of `open`.
=> Fix build using musl libc

HACKING.md, README.md, rpm/touchegg.spec
With these small changes you can have your own copr automatic build and repository for fedora like this one https://copr.fedorainfracloud.org/coprs/jborque/touchegg/
=> Added bits to make automatic fedora copr builds work

CMakeLists.txt, cmake/Modules/FindGIO.cmake
Add missing `libgio` to `target_link_libraries`.
Reported by @oreosec 
Fix https://github.com/JoseExposito/touchegg/issues/511
=> Link libgio

src/gesture-gatherer/libinput-device-handler.cpp, src/gesture-gatherer/libinput-touch-handler.cpp
Once the gesture starts update the value of `startX/Y` with `currentX/Y` to avoid including the `startThreshold` in the percentage calculations.
=> Touch update delta on start

src/window-system/x11.cpp
Hi I tried this project today but had issues with some laggy behavior. 
I figured out that XRRGetScreenResources was cause of the lags, and also found that XRRGetScreenResourcesCurrent is much faster and should be sufficient for this case.
=> Use XRRGetScreenResourcesCurrent for performance

installation/touchegg.conf
As of recently firefox natively supports smooth two finger pinch to zoom gestures on X11 when using the environment variable `MOZ_USE_XINPUT2=1`. Currently touchegg intercepts pinch gestures for firefox by default, resulting in choppy zooming instead. 
To make use of firefox's native gesture support, this PR removes firefox two finger pinch handling from `touchegg.conf`.
=> Config: remove two finger pinch for firefox

src/daemon/dbus.h
FreeBSD does not support abstract Unix sockets, causing the app to crash with error "Error creating D-Bus server: Abstract namespace not supported".
As pointed out by @yurivict, the FreeBSD port of Touchégg patches "src/daemon/dbus.h" to fix this issue:
https://cgit.freebsd.org/ports/tree/sysutils/touchegg/files/patch-src_daemon_dbus.h
Apply a similar patch upstream to fix #611.
=> Do not use abstract socket on FreeBSD

src/gesture/gesture.h
Currently, when compiling with GCC 13, the following error is displayed:
```
In file included from /builddir/build/BUILD/touchegg-2.0.15/src/actions/action.h:26,
from /builddir/build/BUILD/touchegg-2.0.15/src/actions/action.cpp:18:
/builddir/build/BUILD/touchegg-2.0.15/src/gesture/gesture.h:32:58: error: 'uint64_t' has not been declared
32  |          int fingers, DeviceType performedOnDeviceType, uint64_t elapsedTime)
|                                                         ^~~~~~~~
/builddir/build/BUILD/touchegg-2.0.15/src/gesture/gesture.h:72:3: error: 'uint64_t' does not name a type
72  |   uint64_t elapsedTime() const { return this->gestureElapsedTime; }
|   ^~~~~~~~
/builddir/build/BUILD/touchegg-2.0.15/src/gesture/gesture.h:22:1: note: 'uint64_t' is defined in header '<cstdint>'; …
```
=> Add <cstdint> header to avoid compilation errors on GCC 13

README.md
- They PPA signing key may not be installed automatically on all systems.
- Installation through `apt` will not work without the signing key.
- Explicitly mentioning the key id aids those who need to retrieve it manually.
Note that I cannot personally vouch for the validity of the key; that is up to the developer/PPA packager. @JoseExposito can you confirm that [7EA12677D47B593CE22727D4C0FCE32AF6B96252](https://keyserver.ubuntu.com/pks/lookup?search=7EA12677D47B593CE22727D4C0FCE32AF6B96252&hash=on&exact=on&op=index) is the correct PPA signing key? (Either stating it explicitly, or implicitly by merging this commit.)
Closes #602, although it was already closed.
Also aids some users in #604, #578, #472, #466, #462, etcetera in case they attempt manual installation of the  PPA signing key. …
=> Mention PPA signing key in installation instructions

README.md, src/actions/execute-action-on.h, src/actions/mouse-click.cpp, src/actions/mouse-click.h, src/actions/repeated-action.cpp, src/actions/repeated-action.h, src/actions/run-command.cpp, src/actions/run-command.h, src/window-system/window-system.h, src/window-system/x11.cpp, src/window-system/x11.h
Until now, it was only possible to execute the `MOUSE_CLICK`, `SEND_KEYS` and `RUN_COMMAND` actions when the gesture started or when the gesture ended.
Include a third option, `<on>begin-and-end</on>` allowing to run the actions both when the gesture starts and ends.
When this new setting is used, `MOUSE_CLICK` starts presses the mouse button when the gesture starts and releases it when the gesture ends.
In the case of `RUN_COMMAND`, a environment variable is set (`TOUCHEGG_GESTURE_ON`) allowing the executed script to take different actions at the beginning and the end of the gesture.
Closes: https://github.com/JoseExposito/touchegg/issues/665
=> Allow to execute actions on gesture begin and end

src/animations/animation.h
Include cstdint to fix a compile error on gcc 15.
Closes: https://github.com/JoseExposito/touchegg/issues/679
=> Add missing include

CMakeLists.txt
Compatibility with versions of CMake older than 3.5 has been removed from CMake 4.0.
In addition, compatibility with versions of CMake older than 3.10 has been deprecated in CMake 3.31.
Since we don't rely on old features, just update the minimum required version to 3.10.0.
The target version is available even in Debian Bullseye (oldstable) [1].
[1] https://packages.debian.org/bullseye/cmake
Closes: https://github.com/JoseExposito/touchegg/issues/681
=> CMake: Set minimum version to 3.10.0
